version: '3.8'

services:
  nginx:
    container_name: account-registration-nginx
    image: nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    networks:
      - kay-manager-buble
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  app:
    container_name: account-registration-app
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh -c 'npm i && npm run start:dev'
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/app/
    networks:
      - kay-manager-buble

networks:
  kay-manager-buble:
    name: kay-manager-buble
    external: true
    driver: bridge
